// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfo = { version: string, platform: string, arch: string, 
/**
 * Always true. Asserted by a test, surfaced in the About page, and the
 * reason there is no HTTP client anywhere in the dependency tree.
 */
offlineOnly: boolean, };
