// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Background painted underneath transparent pixels when alpha cannot survive.
 */
export type Background = { r: number, g: number, b: number, };
