// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a column's text should be written to a typed output (XLSX/JSON).
 */
export type ColumnType = "text" | "number" | "boolean" | "date" | "automatic";
