// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionError } from "./ConversionError";
import type { FileDescriptor } from "./FileDescriptor";
import type { JobProgress } from "./JobProgress";
import type { JobResult } from "./JobResult";
import type { JobStatus } from "./JobStatus";
import type { OverwritePolicy } from "./OverwritePolicy";
import type { JsonValue } from "./serde_json/JsonValue";

export type ConversionJob = { id: string, operationId: string, inputFiles: Array<FileDescriptor>, outputDirectory: string, overwritePolicy: OverwritePolicy, options: JsonValue, status: JobStatus, progress: JobProgress, createdAt: string, startedAt: string | null, completedAt: string | null, result: JobResult | null, error: ConversionError | null, };
