// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable machine-readable failure taxonomy. These values are part of the CLI
 * contract (`--json`) and must not be renamed without a version bump.
 */
export type ConversionErrorCode = "unsupportedFormat" | "unsupportedCodec" | "invalidInput" | "corruptedInput" | "passwordRequired" | "invalidPassword" | "insufficientDiskSpace" | "insufficientMemory" | "permissionDenied" | "destinationUnavailable" | "toolMissing" | "toolChecksumMismatch" | "processFailed" | "processTimedOut" | "cancelled" | "outputValidationFailed" | "outputLargerThanInput" | "archiveUnsafe" | "internalError";
