// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionErrorCode } from "./ConversionErrorCode";

/**
 * A single error type rather than one enum variant per code: the code *is* the
 * discriminant, and the extra fields are the ones the UI must render to satisfy
 * the "what happened / is my source safe / was partial output removed" contract.
 */
export type ConversionError = { code: ConversionErrorCode, 
/**
 * i18n key resolved by the frontend into a user-facing explanation.
 */
messageKey: string, 
/**
 * Technical detail, shown only behind the "technical details" toggle.
 * Already redacted — see [`redact`].
 */
detail: string, 
/**
 * `true` when the input files are known to be byte-for-byte untouched.
 */
sourceSafe: boolean, 
/**
 * `true` when an invalid or partial output was deleted or quarantined.
 */
partialOutputRemoved: boolean, };
