// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveFormat } from "./ArchiveFormat";

export type CreateOptions = { format: ArchiveFormat, 
/**
 * Base name of the resulting archive, without extension.
 */
archiveName: string | null, 
/**
 * Deflate level 0–9 for ZIP and TAR.GZ. Ignored for plain TAR.
 */
level: number | null, };
