// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectionSource } from "./DetectionSource";
import type { FileFormat } from "./FileFormat";

export type Detection = { format: FileFormat, 
/**
 * 1.0 for a byte signature, 0.3 for an extension guess, 0.0 for nothing.
 */
confidence: number, source: DetectionSource, 
/**
 * `true` when the extension claims a different format than the bytes do.
 * The UI must warn; conversion still proceeds using the detected format.
 */
extensionMismatch: boolean, };
