// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileFormat } from "./FileFormat";
import type { FileMetadata } from "./FileMetadata";

export type FileDescriptor = { id: string, path: string, 
/**
 * File name only — the UI never renders a full path, so a screenshot of a
 * job cannot leak the user's directory structure.
 */
displayName: string, sizeBytes: number, extension: string | null, 
/**
 * Extension-derived MIME hint from the OS, if any. A hint, never a decision.
 */
declaredMime: string | null, detectedFormat: FileFormat, 
/**
 * 1.0 for a byte signature, 0.3 for an extension guess, 0.0 for nothing.
 */
detectionConfidence: number, 
/**
 * `true` when the extension claims a format the bytes contradict.
 */
extensionMismatch: boolean, metadata: FileMetadata, };
