// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Formats LocalConvert intends to handle. Present in full from Phase 0 so the
 * conversion matrix, the UI and the CLI share one vocabulary.
 */
export type FileFormat = "jpeg" | "png" | "webp" | "avif" | "heic" | "tiff" | "bmp" | "gif" | "pdf" | "csv" | "tsv" | "json" | "xlsx" | "mp4" | "mov" | "mkv" | "webm" | "mp3" | "wav" | "flac" | "ogg" | "m4a" | "zip" | "tar" | "tarGz" | "unknown";
