// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Formats this engine can write.
 */
export type ImageOutputFormat = "jpeg" | "png" | "webp" | "tiff" | "bmp";
