// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFilePreflight } from "./ImageFilePreflight";
import type { JobWarning } from "./JobWarning";

/**
 * What the UI shows before the user commits to a batch.
 */
export type ImageBatchPreflight = { files: Array<ImageFilePreflight>, 
/**
 * Deduplicated union across the batch — twenty files losing transparency
 * is one sentence, not twenty.
 */
warnings: Array<JobWarning>, backgroundRequired: boolean, convertibleCount: number, unsupportedCount: number, };
