// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Background } from "./Background";
import type { ImageOutputFormat } from "./ImageOutputFormat";
import type { ResizeSpec } from "./ResizeSpec";

export type ImageOptions = { targetFormat: ImageOutputFormat, 
/**
 * 1–100. Only meaningful for lossy formats; rejected for the others.
 */
quality: number | null, resize: ResizeSpec | null, 
/**
 * Required when the source has transparency and the target cannot keep it.
 */
background: Background | null, };
