// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileFormat } from "./FileFormat";

/**
 * One file's contribution to the preview shown before a batch runs.
 */
export type ImageFilePreflight = { displayName: string, detectedFormat: FileFormat, extensionMismatch: boolean, width: number, height: number, sizeBytes: number, hasAlpha: boolean, isAnimated: boolean, 
/**
 * Set when this particular file cannot be converted. Reported per file so
 * one HEIC among twenty PNGs does not blank the whole preview.
 */
errorMessageKey: string | null, };
