// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobWarning } from "./JobWarning";

/**
 * What a conversion will cost the user, computed before it runs so the UI can
 * explain it and the user can decline. Spec §4.3.
 */
export type ImagePreflight = { sourceWidth: number, sourceHeight: number, hasAlpha: boolean, isAnimated: boolean, hasMetadata: boolean, 
/**
 * The target cannot keep this image's transparency, so a background must
 * be chosen before the job can start.
 */
backgroundRequired: boolean, warnings: Array<JobWarning>, };
