// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressStage } from "./ProgressStage";

/**
 * Honest progress.
 *
 * `percent` is `None` whenever the underlying engine cannot report real
 * progress; the UI then shows an indeterminate bar and the stage label. There
 * is deliberately no synthetic "estimated" percentage anywhere in the codebase.
 */
export type JobProgress = { stage: ProgressStage, completedUnits: number | null, totalUnits: number | null, percent: number | null, messageKey: string, };
