// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobWarning } from "./JobWarning";
import type { OutputDescriptor } from "./OutputDescriptor";
import type { ValidationReport } from "./ValidationReport";

export type JobResult = { outputs: Array<OutputDescriptor>, warnings: Array<JobWarning>, validationReports: Array<ValidationReport>, elapsedMs: number, inputTotalBytes: number, outputTotalBytes: number, sizeChangePercent: number, };
