// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobWarning = { 
/**
 * i18n key, e.g. `warning.image.transparencyLost`.
 */
messageKey: string, detail: string | null, };
