// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaFormat } from "./MediaFormat";
import type { MediaPreset } from "./MediaPreset";
import type { Trim } from "./Trim";

export type MediaOptions = { targetFormat: MediaFormat, preset: MediaPreset, 
/**
 * Optional trim applied before encoding.
 */
trim: Trim | null, 
/**
 * Drop the audio stream from a video output.
 */
removeAudio: boolean, };
