// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationCategory } from "./OperationCategory";
import type { OperationStability } from "./OperationStability";

export type OperationDescriptor = { id: string, category: OperationCategory, stability: OperationStability, labelKey: string, descriptionKey: string, 
/**
 * Lowercase extensions accepted as input. Empty means the operation takes
 * no input files.
 */
inputExtensions: Array<string>, 
/**
 * Lowercase extensions this operation can produce.
 */
outputExtensions: Array<string>, 
/**
 * `true` when the operation consumes several inputs at once (merge, archive)
 * or processes a batch.
 */
acceptsMultipleInputs: boolean, };
