// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors the status column of `docs/CONVERSION_MATRIX.md`. Only `Stable`
 * operations are shown in the main tool sections.
 */
export type OperationStability = "experimental" | "beta" | "stable";
