// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format-specific facts read back off the finished file. Kept as free-form
 * JSON rather than a union of every media type: each plugin owns its own
 * shape, and the UI renders whatever keys it recognises.
 */
export type OutputMetadata = { sizeBytes: number, properties: Record<string, unknown>, };
