// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse stage shown next to the progress bar.
 */
export type ProgressStage = "queued" | "preparing" | "running" | "validating" | "finalizing" | "done";
