// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResizeSpec = { "mode": "fit", maxWidth: number, maxHeight: number, } | { "mode": "exact", width: number, height: number, };
