// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnType } from "./ColumnType";
import type { TabularFormat } from "./TabularFormat";

export type SpreadsheetOptions = { targetFormat: TabularFormat, 
/**
 * Delimiter override for reading a CSV/TSV, as a single character. `None`
 * means detect it.
 */
delimiter: string | null, 
/**
 * `true` (default) treats the first row as column names.
 */
hasHeader: boolean, 
/**
 * Which sheet to read from an XLSX. `None` reads the first.
 */
sheet: string | null, 
/**
 * Per-column type by header name. Anything unlisted defaults to `Text`.
 */
columnTypes: { [key in string]?: ColumnType }, 
/**
 * Write a UTF-8 BOM into CSV/TSV output (helps legacy Excel on Windows).
 */
writeBom: boolean, };
