// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverwritePolicy } from "./OverwritePolicy";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * What the frontend sends to start work. Deliberately narrow: no command
 * strings, no engine arguments, no arbitrary paths beyond the selected inputs
 * and one destination directory.
 */
export type StartJobRequest = { operationId: string, inputPaths: Array<string>, outputDirectory: string, overwritePolicy: OverwritePolicy, 
/**
 * Operation-specific options, validated against the operation's schema by
 * the owning plugin before execution.
 */
options: JsonValue, };
