// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Trim = { 
/**
 * Start offset in seconds.
 */
start: number, 
/**
 * Duration in seconds from the start offset.
 */
duration: number, };
