// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named assertion about an output file.
 */
export type ValidationCheck = { 
/**
 * Stable identifier, e.g. `output.exists`, `image.dimensionsMatch`.
 */
id: string, passed: boolean, detail: string | null, };
