// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputMetadata } from "./OutputMetadata";
import type { ValidationCheck } from "./ValidationCheck";

export type ValidationReport = { valid: boolean, detectedFormat: string, warnings: Array<string>, checks: Array<ValidationCheck>, outputMetadata: OutputMetadata, };
